services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8081:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: ./php
    container_name: php83
    volumes:
      - ./app:/var/www/html

volumes:
  php_code: