services:

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8081:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../app:/var/www/html
    networks:
      - my_network
    depends_on:
      - php

  php:
    build:
      context: ./php
    container_name: php83
    volumes:
      - ../app:/var/www/html
    networks:
      - my_network
    depends_on:
      - database
    

  database:
    container_name: mysql
    restart: unless-stopped
    image: mariadb:lts-jammy
    ports:
      - "3381:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - my_network

networks:
    my_network:
      driver: bridge